#!/usr/bin/python

import hashlib
import sys


def tosha1(path):
    sha1 = hashlib.sha1()
    with open(path) as f:
        sha1.update(f.read())

    return sha1.hexdigest()


if __name__ == '__main__':
    for name in sys.argv[1:]:
        print(name, tosha1(name))
